version: "3"
services:
  redis:
    image: redis
  datahub-invest-fe:
    env_file:
     - .env
    build:
      context: .
    ports:
      - 3000:3000
      - 5858:5858
      - 9229:9229
    environment:
     - API_ROOT
     - API_CLIENT_ID
     - API_CLIENT_SECRET
     - POSTCODE_KEY
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
      - ./build:/usr/src/app/build
    command: npm run develop
    links:
      - redis
