# Documentation: https://dependabot.com/docs/config-file

version: 1
update_configs:
  - package_manager: javascript
    directory: '/'
    update_schedule: weekly
    ignored_updates:
      - match:
          dependency_name: 'govuk-frontend'
      - match:
          dependency_name: 'govuk-colours'
      - match:
          dependency_name: 'image-webpack-loader'
